name: Generate Snake

on:
  schedule:
    # Her gün 05:00 UTC'de çalıştır
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Contributions Snake
        uses: Platane/snk@master
        with:
          github_user_name: <ufukatici>
          outputs: dist/snake.svg

      - name: Publish Snake Game
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
